"""empty message

Revision ID: 4b83a4687bd2
Revises: fa538d86cd20
Create Date: 2020-04-04 11:56:09.464934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b83a4687bd2'
down_revision = 'fa538d86cd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location_combined_key_key', 'location', type_='unique')
    op.add_column('user', sa.Column('flagged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'flagged')
    op.create_unique_constraint('location_combined_key_key', 'location', ['combined_key'])
    # ### end Alembic commands ###
