"""initial migration

Revision ID: 8495a85a6a09
Revises: 
Create Date: 2020-04-04 11:19:23.727363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8495a85a6a09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location_combined_key_key', 'location', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('location_combined_key_key', 'location', ['combined_key'])
    # ### end Alembic commands ###
